config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/generate_otp', to: 'users/sessions#generate_otp', as: :generate_otp
    get '/session_id/:id', to: 'users/sessions#session_id', as: :session_id
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  
  resources :pages, controller: 'pages' do
    member do
      post :follow
      delete :unfollow
    end
  end

  resources :groups do
    member do
      post 'follow'
      delete 'unfollow'
      get 'followers', to: 'groups#followers', as: 'group_followers'
    end
  end
  
  # for hide & unhide the posts
  resources :posts do
    member do
      post 'hide'
      post 'undo_hide'
      post 'toggle_hide'
      post 'repost_with_thought', to: 'reposts#repost_with_thought', as: 'repost_thought'
    end
    resources :reposts
    resources :comments
    resources :user_reactions, only: [:create, :destroy]
  end

  resources :events do
    collection do
      get 'calendar', to: 'events#calendar'
      post 'calendar_events', to: 'events#create_calendar_event'
    end
  end


  get 'hidden_posts', to: 'posts#hidden'

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get '/search_results', to: 'search#results', as: 'search_results'
  
  get '/home', to: 'home#index', as: :home
  get '/home/sort', to: 'home#sort', as: :home_sort
  
  get 'member/:id', to: 'members#show', as: :member  
  get 'member/:id/edit', to: 'members#edit', as: :edit_member
  patch 'member/:id', to: 'members#update', as: :update_member

  get 'members/fetch_country_states', to: 'members#fetch_country_states', as: :fetch_country_states

  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: 'update_member_personal_details'

  get 'member-connections/:id', to: 'members#connections', as: 'member_connections'

  resources :articles  
  resources :jobs
  resources :job_categories
  resources :work_experiences
  resources :connections
  resources :skills
  resources :shares, only: [:new, :create,:index]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]

  resources :users do
    resources :posts
    resources :jobs
    resources :my_jobs, only: [:index]
    resources :my_events, only: [:index]
    resources :my_articles, only: [:index]
  end

  resources :members, controllers: 'members' do
    member do
      post :follow
      delete :unfollow
      get :followers_and_following
    end
    collection do
      get :fetch_country_states
    end
  end

  resources :followers, only: [:show] do
    member do
      get :show_followers
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def suggestions
    @results = search_results

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
            turbo_stream.update('suggestions',
                                partial: 'search/suggestions',
                                locals: { results: @results })
      end
    end
  end

  def results
    @user = User.includes(following: { posts: [:comments, :likes] }, posts: [:comments, :likes], image_attachment: :blob).find(params[:user_id])
    @posts = @user.posts
    @mutual_connections = current_user.mutually_connected_ids(@user)
    @post_likes_count = @posts.joins(:likes).group('posts.id').count

    comment_counts = Comment.where(commentable_id: @posts.map(&:id), commentable_type: 'Post')
                           .group(:commentable_id)
                           .count
    @post_comment_counts = comment_counts.transform_keys(&:to_i)
    @people_i_follow_count = @user.following.size
  end



  private

  def search_results
    query = params[:query]
    User.where("first_name ILIKE ? OR last_name ILIKE ?", "%#{query}%", "%#{query}%") +
    Post.where("title ILIKE ?", "%#{query}%") + 
    Job.where("title ILIKE ?", "%#{query}%") + 
    Event.where("event_name ILIKE ?", "%#{query}%") + 
    Page.where("title ILIKE ? OR content ILIKE ?", "%#{query}%", "%#{query}%")
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :post, class: "w-60", data: {
    controller: "search",
    action: "keyup->search#suggestions",
    suggestions_url: search_suggestions_path,
}) do |form| %>
  <div class="relative">
    <%= form.text_field :query, data: {
            search_target: "input",
            action: "blur->search#hideSuggestions",
        },
        class: "form-control",
        placeholder: "Search Post, Jobs, Users, Events, Pages..",
        autocomplete: "off" %>
    <div id="suggestions" class="absolute"
        data-search-target="suggestions" data-action="mousedown->search#childClicked">
      <%= render partial: "search/suggestions", locals: { results: results } %>
    </div>
  </div>
<% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
  <div class="position-absolute overflow-auto max-height: 200px; bg-white rounded shadow" id="search">
    <% results.each do |result| %>
      <div class="p-2 border-bottom">
        <% if result.is_a?(User) %>
          <%= link_to "#{result.first_name} #{result.last_name} (User)", search_results_path(user_id: result.id), class: "text-primary", style: "text-decoration:none;" %>
        <% elsif result.is_a?(Post) %>
          <%= link_to "#{result.title} (Post)", post_path(result), class: "text-primary", style: "text-decoration:none;" %>
        <% elsif result.is_a?(Job) %>
          <%= link_to "#{result.title} (Job)", job_path(result), class: "text-primary", style: "text-decoration:none;" %>
        <% elsif result.is_a?(Event) %>
          <%= link_to "#{result.event_name} (Event)", event_path(result), class: "text-primary", style: "text-decoration:none;" %>
        <% elsif result.is_a?(Page) %>
          <%= link_to "#{result.title} (Page)", page_path(result), class: "text-primary", style: "text-decoration:none;" %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>


<style>
  #search{
    z-index: 99;
    height: 300px;
  }
</style>

app/views/search/results.html.erb
<div class="col-lg-10 mx-auto mt-3">
  <div class="row">
    <div class="col-lg-4">
      <div class="card shadow mb-2 mt-2 rounded-0">
        <div class="card-body">
          <small class="text-muted">on this page</small>
          <% if @people_i_follow_count.present? && @people_i_follow_count > 0 %>
            <div id="people-i-follow-count">
              <%= link_to "People I Follow (#{@people_i_follow_count})", followers_and_following_member_path(@user), style: "text-decoration:none;" %>
            </div>
          <% end %>          
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card shadow mb-2 mt-2 rounded-0">
        <div class="row">
          <div class="col-lg-2">
            <% if @user.image.attached? %>
              <%= image_tag @user.image, style: "width: 200px; max-width:100%; max-height:100%; height:auto", class: 'border border-1 rounded-circle mt-2 mx-3' %>
            <% else %> 
              <%= image_tag 'human.avif', style: "width: 200px; max-width:100%; max-height:100%; height:auto", class: 'border border-2 rounded-circle mt-2 mx-3' %>
            <% end %>
          </div>
          <div class="col-lg-10">
            <div class="card-body">
              <h3><%= @user.name %></h3>
                <small class="text-muted"><%= @user.profile_title %></small><br>
                <small>
                  <% if @mutual_connections.present? && @mutual_connections.count > 0 %>
                    <%= link_to pluralize(@mutual_connections.count, 'mutual connection'), member_connections_path(@user, mutual_connection: true), style: "text-decoration:none;" %>
                  <% end %>
                </small>
                <br>
                <%= link_to 'View Profile', member_path(@user), class: 'btn btn-outline-primary btn-sm mt-2 rounded-pill' %>
            </div>
          </div>
        </div>
      </div>
      <div data-controller="show-more-posts" data-show-more-posts-hidden-class="hidden" data-show-more-posts-target="post">
        <% if @posts.present? %>
          <% @posts.each_with_index do |post, index| %>
            <div class="post <%= "hidden" if index >= 3 %>" data-show-more-posts-target="post">
              <div class="card shadow mt-2 mb-2 rounded-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-1 col-12 mb-2 d-grid">
                      <%= link_to member_path(post.user), style: "text-decoration:none;" do %>
                        <% if post.user.image.attached? %>
                          <%= image_tag post.user.image, class: "border border-2 rounded-circle user-image" %>
                        <% else %> 
                          <%= image_tag 'human.avif', class: "border border-2 rounded-circle user-image" %>
                          <% end %>
                      <% end %>
                    </div>
                    <div class="col-md-10 col-12 mt-2 mb-3 d-grid">
                      <%= link_to member_path(post.user), style: "text-decoration:none;" do %>
                        <h5 class="text-dark mx-md-5 mx-2"><%= post.user.name %></h5>
                        <small class="text-muted mx-md-5 mx-2"><%= truncate(post.user.profile_title, length: 25) %></small>
                        <br>
                        <small class="text-muted mx-md-5 mx-2">Posted <%= time_ago_in_words(post.created_at) %> ago</small>
                      <% end %>
                    </div>
                    <div class="col-md-1 col-12 mt-1 mb-3 d-grid justify-content-end">
                      <div class="dropdown">
                        <a href="#" class="text-decoration-none text-reset" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fa-solid fa-ellipsis fa-xl mt-3"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                          <% if current_user == post.user %>
                            <li>
                              <%= link_to 'Delete', post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are You Sure to delete ?" }, class: "dropdown-item" %>
                            </li>
                            <li>
                              <%= link_to 'Edit', edit_post_path(post), data: { controller: 'bs-modal-form' }, class: "dropdown-item" %>
                            </li>
                          <% end %>
                          <li>
                            <%= link_to 'View', post_path(post), class: 'dropdown-item' %>
                          </li>
                          <li>
                            <button
                              data-controller="copy-url"
                              data-copy-url-target="copyButton"
                              data-copy-url-post-id="<%= post.id %>"
                              data-action="click->copy-url#copyUrl"
                              class="dropdown-item"
                              >
                                Copy URL
                            </button>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="user-info mt-2" data-controller="user-name">
                    <h5 data-user-name-target='name'><%= post.title %> </h5>
                    <div data-controller= "show-more">
                      <div data-show-more-target="description">
                        <p><%= simple_format(post.description) %></p>
                      </div>
                      <div class="col-lg-12 d-flex justify-content-end">
                        <button 
                          data-action="click->show-more#toggleVisibility" 
                          data-show-more-target="toggleButton" 
                          class="btn btn-outline-light text-primary btn-sm mb-3 mt-3">
                          Show More
                        </button>
                      </div>
                      <div class="col-lg-12 mb-1 d-flex justify-content-end">
                        <% if (@post_comment_counts[post.id] || 0) > 0 %>
                          <%= link_to post_path(post), style: "text-decoration:none;" do %>
                            <%= pluralize(@post_comment_counts[post.id], "Comment") %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div>
                    <%= link_to post_path(post) do %>
                      <% if post.images.attached? %>
                        <% post.images.each do |image| %>
                          <% if image.content_type.include?("image") %>
                            <a href="<%= rails_blob_path(image) %>" class="post_images me-2 mb-3 mt-3" data-turbolinks="false" data-mfp-title="<%= post.title %>">
                              <%= image_tag image, style: 'width: 300px; height: 250px;', class: 'mt-2 mb-2 border border-4' %>
                            </a>
                          <% else %>
                            <div class="bg-dark text-center">
                              <%= video_tag rails_blob_path(image), autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video", controls: true, type: 'video/mp4', style: "max-width: 100%; height: 320px;" do %>
                                Your browser does not support the video tag.
                              <% end %>
                            </div>
                          <% end %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="row mt-3">
                    <div class="col-lg-1 col-md-2 col-3">
                      <% if user_signed_in? %>
                        <% like = post.likes.find { |like| like.user_id == current_user.id } %>
                        <% if like.nil? %>
                          <%= button_to likes_path, params: { like: { post_id: post.id } }, method: :post, class: "btn btn-light position-absolute mt-2" do %>
                            <i class="fa-solid fa-thumbs-up fa-xl" title="Like"></i>
                          <% end -%>
                        <% else %>
                          <%= button_to like_path(like), params: { like: { post_id: post.id } }, method: :delete, class: "btn btn-light position-absolute mt-2" do %>
                            <i class="fa-solid fa-thumbs-down fa-xl" title="Dislike"></i>
                          <% end -%>
                        <% end -%>
                      <% end -%>
                      <% if @post_likes_count[post.id].to_i > 0 %>
                        <span class="position-relative top-0 translate-middle badge rounded-pill bg-danger"><%= @post_likes_count[post.id] %></span>
                      <% end %>
                    </div>
                    <div class="col-lg-1 col-md-2 col-3">
                      <%= link_to new_share_path(post_id: post.id), class: "btn btn-light mt-2", data: { controller: "bs-modal-form" } do %>
                          <i class="fa-solid fa-paper-plane" title="Share"></i>
                      <% end %>
                    </div>
                    <div class="col-lg-1 col-md-2 col-3">
                      <div class="dropdown">
                        <button class="btn btn-light mt-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fa-solid fa-share-from-square" title="Share on Social Media"></i>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                          <li>
                            <a href="https://www.facebook.com/sharer/sharer.php?u=<%= ENV['APP_URL']%><%= post_path(post)%>" target="_blank" class="dropdown-item">Share on Facebook</a>
                          </li>
                          <li>
                            <a class="dropdown-item" href="https://twitter.com/intent/tweet?url=<%= ENV['APP_URL']%><%= post_path(post)%>&text=<%= post.title %>" target="_blank">Share on Twitter</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-1 col-md-2 col-3">
                      <% if user_signed_in? %>
                        <% if current_user.has_reposted?(post) %>
                          <%= link_to [post, current_user.repost_for(post)], method: :delete, class: 'btn btn-light mt-2', title: "Remove Repost" do %>
                            <i class="fa-solid fa-repeat"></i>
                          <% end %>
                        <% else %>
                          <%= link_to post_reposts_path(post), method: :post, class: 'btn btn-light mt-2', title: "Repost" do %>
                          <i class="fa-solid fa-repeat"></i>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <% if @posts.length > 2 %>  
              <button data-action="click->show-more-posts#showMore" data-show-more-posts-target="showMore" class="btn btn-outline-dark w-100 mt-2 shadow">Show More Posts</button>
              <button data-action="click->show-more-posts#showLess" data-show-more-posts-target="showLess" class="hidden btn btn-outline-dark w-100 mt-2 shadow">Show Less Posts</button>
          <% end %>
          <% else %>
            <h4 class="mt-3">No post is available</h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.post_images').magnificPopup({
      type: 'image',
      gallery: {
        enabled: true
      },
      mainClass: 'mfp-with-zoom',
      zoom: {
        enabled: true,
        duration: 300,
        easing: 'ease-in-out'
      }
    });
  });
</script>