config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/generate_otp', to: 'users/sessions#generate_otp', as: :generate_otp
    get '/session_id/:id', to: 'users/sessions#session_id', as: :session_id
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  
  resources :pages, controller: 'pages' do
    member do
      post :follow
      delete :unfollow
    end
  end

  resources :groups do
    member do
      post 'follow'
      delete 'unfollow'
      get 'followers', to: 'groups#followers', as: 'group_followers'
    end
  end
  
  # for hide & unhide the posts
  resources :posts do
    member do
      post 'hide'
      post 'undo_hide'
      post 'toggle_hide'
      post 'repost_with_thought', to: 'reposts#repost_with_thought', as: 'repost_thought'
    end
    resources :reposts
    resources :comments
    resources :user_reactions, only: [:create, :destroy]
  end

  resources :events do
    collection do
      get 'calendar', to: 'events#calendar'
      post 'calendar_events', to: 'events#create_calendar_event'
    end
  end


  get 'hidden_posts', to: 'posts#hidden'

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get '/search_results', to: 'search#results', as: 'search_results'
  
  get '/home', to: 'home#index', as: :home
  get '/home/sort', to: 'home#sort', as: :home_sort
  
  get 'member/:id', to: 'members#show', as: :member  
  get 'member/:id/edit', to: 'members#edit', as: :edit_member
  patch 'member/:id', to: 'members#update', as: :update_member

  get 'members/fetch_country_states', to: 'members#fetch_country_states', as: :fetch_country_states

  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: 'update_member_personal_details'

  get 'member-connections/:id', to: 'members#connections', as: 'member_connections'

  resources :articles  
  resources :jobs
  resources :job_categories
  resources :work_experiences
  resources :connections
  resources :skills
  resources :shares, only: [:new, :create,:index]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]

  resources :users do
    resources :posts
    resources :jobs
    resources :my_jobs, only: [:index]
    resources :my_events, only: [:index]
    resources :my_articles, only: [:index]
  end

  resources :members, controllers: 'members' do
    member do
      post :follow
      delete :unfollow
      get :followers_and_following
    end
    collection do
      get :fetch_country_states
    end
  end

  resources :followers, only: [:show] do
    member do
      get :show_followers
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  
  has_and_belongs_to_many :users
  has_many :posts
  has_one_attached :image

  INDUSTRY = [  'Software Development',
                'Data Security Software Products',
                'Desktop Computing Software Products',
                'Mobile Computing Software Products',
                'Embedded Software Products',
                'IT Service and IT Consulting',
                'IT System Testing and Evaluation',
                'IT System Data Services',
                'IT System Custom Software Development',
                'IT System Training and Support',
                'IT System Installation and Disposal'
              ]
              
  GROUP_TYPE = ['Public', 'Private']
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_groups, only: %i[edit show update destroy follow unfollow followers]

  def index
    @groups = Group.includes(:user).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to groups_path, notice: "Group was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def show
    @groups = Group.all
    @group = Group.includes(posts: [{ user: { likes: :user } }, { comments: :user }, { user_reactions: :user }, { images_attachments: :blob }]).find(params[:id])

    # Load associated users for likes and comments
    @users_for_likes = User.where(id: @group.posts.joins(:likes).pluck('likes.user_id').uniq)
    @users_for_comments = User.where(id: @group.posts.joins(:comments).pluck('comments.user_id').uniq)

    @posts = @group.posts
    @post_likes_count = Post.joins(:likes).group('posts.id').count
    comment_counts = Comment.where(commentable_id: @posts.map(&:id), 
                     commentable_type: 'Post')
                     .group(:commentable_id)
                     .count
    @post_comment_counts = comment_counts.transform_keys(&:to_i)
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: "Group was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    if @group.destroy
      redirect_to groups_path, alert: "Group was deleted!"
    end
  end

  def follow
    current_user.groups << @group unless current_user.groups.include?(@group)
    redirect_to @group, notice: 'You have followed the group.'
  end

  def unfollow
    current_user.groups.delete(@group) if current_user.groups.include?(@group)
    redirect_to @group, alert: 'You have unfollowed the group.'
  end

  def followers
    @followers = @group.users
  end

  private

  def set_groups
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description, :industry, :group_type, :location, :user_id, :image)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group do |form| %>
  <div class="modal-body">
    <div class="form-group">
       <%= form.hidden_field :user_id, value:current_user.id %>
    </div>

    <div class="form-group">
      <%= form.label :group_name %>
      <%= form.text_field :name, class: 'form-control mt-2 mb-2' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control mt-2 mb-2' %>
    </div>

    <div class="form-group">
      <%= form.label :group_industry %>
      <%= form.select :industry, options_for_select(Group::INDUSTRY, selected: form.object.industry ),{prompt: 'Select Group Industry'},  {class: 'form-select mt-2 mb-2'} %>
    </div>

    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: 'form-control mt-2 mb-2' %>
    </div>

    <div class="form-group">
      <%= form.label :group_type %>
      <%= form.select :group_type, options_for_select(Group::GROUP_TYPE, selected: form.object.group_type ),{prompt: 'Select Group Type'},  {class: 'form-select mt-2 mb-2'} %>
    </div> 

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control mt-2 mb-2' %>
    </div> 

    <div class="form-group mt-2 mb-2">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', groups_path, class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

app/views/groups/_group_posts.html.erb
<div class="mt-2 mb-2" id="post-list" >
  <% if @group.posts.present? %>
    <% @group.posts.each do |post| %>
      <% if post.group_id.present? %>
        <div class="card mb-2 shadow" style="min-height: 320px;">
          <div class="card-body">
            <div class="container">
              <div class="row post-info">
                <div class="col-md-1 col-12 mb-2 d-grid post-user-image">
                  <%= link_to member_path(post.user), style: "text-decoration:none;" do %>
                    <% if post.user.image.attached? %>
                      <%= image_tag post.user.image, class: "user-image border border-1 rounded-circle" %>
                    <% else %> 
                      <%= image_tag 'human.avif', class: "user-image border border-1 rounded-circle" %>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-md-8 col-12 mt-2 mb-3 px-5 d-grid post-user-details">
                  <%= link_to member_path(post.user), style: "text-decoration:none;" do %>
                    <h5 class="text-dark post-user-name"><%= post.user.name %></h5>
                    <small class="text-muted post-user-title"><%= truncate(post.user.profile_title, length: 25) %></small><br>
                    <small class="text-muted post-time-ago">Posted <%= time_ago_in_words(post.created_at) %> ago</small>
                  <% end %>
                </div>
                <div class="col-md-1 col-12 mt-2 mb-3 px-3 justify-content-end post-follow-button">
                  <% if current_user != post.user %>
                    <% if current_user.following?(post.user) %>
                      <%= link_to 'Unfollow', unfollow_member_path(post.user), method: :delete, class: 'btn btn-outline-danger btn-sm fw-bold', style: "text-decoration:none;" %>
                    <% else %>
                      <%= link_to 'Follow', follow_member_path(post.user), method: :post, class: "btn btn-outline-primary btn-sm fw-bold", style: 'text-decoration:none;' %>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-md-1 col-12 mt-1 mb-3 px-3 d-grid justify-content-end post-more-options">
                  <div class="dropdown">
                    <a href="#" class="text-decoration-none text-reset" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fa-solid fa-ellipsis fa-xl mt-3"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <% if current_user == post.user %> 
                        <li><%= link_to 'Delete', post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are You Sure to delete ?" }, class: "dropdown-item" %></li>
                        <li><%= link_to 'Edit', edit_post_path(post), data: { controller: 'bs-modal-form' }, class: "dropdown-item" %></li>
                      <% end %>
                      <li><%= link_to 'View', post_path(post), class: 'dropdown-item' %></li>
                      <li>
                        <button
                          data-controller="copy-url"
                          data-copy-url-target="copyButton"
                          data-copy-url-post-id="<%= post.id %>"
                          data-action="click->copy-url#copyUrl"
                          class="dropdown-item"
                        >
                          Copy URL
                        </button>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="col-md-1 col-12 mt-2 mb-3 px-3 d-grid justify-content-end" data-controller="hide-post" data-hide-post-post-id="<%= post.id %>">
                  <%= link_to hide_post_path(post), method: :post, class: 'hide-post', title: 'hide-post', data: { action: "click->hide-post#hidePost" } do  %>
                    <i class="fa-solid fa-xmark"></i>
                  <% end %>  
                  <%# <div class="hide-dialog" data-hide-post-target="dialog">
                    <p>Post removed from your feed</p>
                    <p>Your feedback helps improve the feed.</p>
                    <%#= link_to undo_hide_post_path(post), method: :post, class:"undo-hide-post", title: 'undo-post', data: { action: "click->hide-post#undoHidePost", hide_post_target: "undoButton" } do %>
                      <%# <i class="fa-solid fa-rotate-left"></i> %>
                    <%# end %>
                  </div> %>                
                </div>
              </div>
            </div>
            <div class="user-info mt-2" data-controller="user-name">
              <%= link_to post_path(post), style: 'text-decoration:none; color: black;' do %>
                <h5 data-user-name-target='name'><%= post.title %> </h5>
                <div data-controller="show-more">
                  <div data-show-more-target="description">
                    <p><%= simple_format(post.description) %></p>
                  </div>
              <% end %>
                  <div class="row">
                     <div class="col-lg-12 d-flex justify-content-end">
                        <button 
                          data-action="click->show-more#toggleVisibility" 
                          data-show-more-target="toggleButton" 
                          class="btn btn-outline-light text-primary btn-sm mb-3 mt-3">
                          Show More
                        </button>
                     </div>
                  </div>
                  <div class="col-lg-12 mb-1 d-flex justify-content-end">
                    <% if (@post_comment_counts[post.id] || 0) > 0 %>
                      <%= link_to post_path(post), style: "text-decoration:none;" do %>
                        <%= pluralize(@post_comment_counts[post.id], "Comment") %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
            </div>
            <div>
              <%= link_to post_path(post) do %>
                <% if post.images.attached? %>
                  <% post.images.each do |image| %>
                    <% if image.content_type.include?("image") %>
                      <a href="<%= rails_blob_path(image) %>" class="post_images me-2 mb-3 mt-3" data-turbolinks="false" data-mfp-title="<%= post.title %>">
                        <%= image_tag image, style: 'width: 370px; height: 280px; max-width: 100%;', class: 'mt-2 mb-2 border border-1' %>
                      </a>
                    <% else %>
                      <div class="bg-dark text-center">
                        <%= video_tag rails_blob_path(image), autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video", controls: true, type: 'video/mp4', style: "max-width: 100%; height: 320px;" do %>
                          Your browser does not support the video tag.
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <!-- for display the names of users who liked & repost a post and show the count of remaining users into the modal popup -->
            <%= render 'home/like_and_reposts', post: post %>

            <div class="row mt-3">
              <div class="col-lg-1 col-md-2 col-3">
                <% if user_signed_in? %>
                  <% like = post.likes.find { |like| like.user_id == current_user.id } %>
                  <% if like.nil? %>
                    <%= button_to likes_path, params: { like: { post_id: post.id } }, method: :post, class: "btn btn-light position-absolute mt-2" do %>
                      <i class="fa-solid fa-thumbs-up fa-xl" title="Like"></i>
                    <% end -%>
                  <% else %>
                    <%= button_to like_path(like), params: { like: { post_id: post.id } }, method: :delete, class: "btn btn-light position-absolute mt-2" do %>
                      <i class="fa-solid fa-thumbs-down fa-xl" title="Dislike"></i>
                    <% end -%>
                  <% end -%>
                <% end -%>
                 <% if @post_likes_count[post.id].to_i > 0 %>
                  <span class="position-relative top-0 translate-middle badge rounded-pill bg-danger"><%= @post_likes_count[post.id] %></span>
                <% end %>
              </div>
              <div class="col-lg-1 col-md-2 col-3">
                <%= link_to new_share_path(post_id: post.id), class: "btn btn-light mt-2", data: { controller: "bs-modal-form" } do %>
                    <i class="fa-solid fa-paper-plane" title="Share"></i>
                <% end %>
              </div>
              <div class="col-lg-1 col-md-2 col-3">
                <div class="dropdown">
                  <button class="btn btn-light mt-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-share-from-square" title="Share on Social Media"></i>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= ENV['APP_URL']%><%= post_path(post)%>" target="_blank" class="dropdown-item">Share on Facebook</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="https://twitter.com/intent/tweet?url=<%= ENV['APP_URL']%><%= post_path(post)%>&text=<%= post.title %>" target="_blank">Share on Twitter</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-1 col-md-2 col-3">
                <% if user_signed_in? %>
                  <% if current_user.has_reposted?(post) %>
                    <%= link_to [post, current_user.repost_for(post)], method: :delete, class: 'btn btn-light mt-2', title: "Remove Repost" do %>
                      <i class="fa-solid fa-repeat"></i>
                    <% end %>
                  <% else %>
                    <%= link_to post_reposts_path(post), method: :post, class: 'btn btn-light mt-2', title: "Repost" do %>
                    <i class="fa-solid fa-repeat"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <div class="col-lg-7 col-md-2 col-3">
                <%= render 'posts/show', post: post %>
              </div>
            </div>
          </div>
          </div>
      <% end %>
    <% end %>
  <% else %>
    <p class="border border-1 rounded p-2">No group post is available</p>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('.post_images').magnificPopup({
      type: 'image',
      gallery: {
        enabled: true
      },
      mainClass: 'mfp-with-zoom',
      zoom: {
        enabled: true,
        duration: 300,
        easing: 'ease-in-out'
      }
    });
  });
</script>

app/views/groups/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
<%= render 'shared/turbo_modal', modal_title: 'Edit Group', form_partial: 'groups/form' %>
<% end %>

app/views/groups/followers.html.erb
<div class="col-lg-10 mx-auto mt-3">
  <h4>Followers of <%= @group.name %></h4>
  <% if @followers.present? %>
    <% @followers.each do |follower| %>
      <div class="card mb-2 shadow">
      <div class="row">
        <div class="col-lg-1">
          <% if follower.image.attached? %>
            <%= image_tag follower.image, class: "user-image mt-3 py-1 mx-2", style: "width:70px;" %>
          <% else %>
            <%= image_tag 'human.avif', class: "user-image mt-3 py-1 mx-2", style: "width:70px;" %>
          <% end %>
        </div>
        <div class="col-lg-9 mt-2">
          <div class="card-body">
            <%= link_to member_path(follower), style: "text-decoration:none;", target: "_blank" do %>
              <h4 style="margin-bottom: -2px;"><%= follower.name %></h4>
            <% end %>
            <small class="text-muted"><%= follower.profile_title %></small><br>
            <small class="text-muted"><%= follower.email %></small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% else %>
    <p class="border border-1 rounded p-2">No followers are present.</p>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-lg-10 mx-auto mt-3">
  <%= link_to 'Create Group', new_group_path, class: "btn btn-outline-primary mb-3", data: { controller: "bs-modal-form" } %>
  <% @groups.each do |group|%>
    <div class="card shadow mb-1">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-9">
            <%= link_to group_path(group), style: 'text-decoration:none;' do %>
              <h5><%= group.name %></h5>
            <% end %>
          </div>
          <div class="col-lg-3">
            <% if current_user && current_user.id == group.user_id %>
              <%= link_to 'View', group_path(group), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-primary btn-sm', data: { controller: "bs-modal-form" } %>
              <%= link_to 'Delete', group_path(group), class: 'btn btn-danger btn-sm', data: { turbo_method: :delete, turbo_confirm: 'Are You Sure?' } %>
            <% else %>
              <%= link_to 'View', group_path(group), class: 'btn btn-primary btn-sm' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>    
  <% end %>
</div>

app/views/groups/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
<%= render 'shared/turbo_modal', modal_title: 'Create Group', form_partial: 'groups/form' %>
<% end %>

app/views/groups/show.html.erb
<div class="container col-lg-10 mx-auto mt-3 my-container">
  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-12 mt-3">
      <div class="card text-center mb-2 shadow current_user_profile">
        <div class="card-body">
          <% if current_user.image.attached? %>
            <%= image_tag current_user.image, style: "width: 80px; max-width:100%;", class: 'border border-1 rounded-circle mb-3 mt-3' %>
          <% else %> 
            <%= image_tag 'human.avif', class: "border border-1 rounded-circle mb-3 mt-3", style: "width: 130px; max-width:100%;" %>
          <% end %>
          <%= link_to member_path(current_user), style: "text-decoration:none;" do %>
            <h5 class="text-dark"><%= current_user.name %></h5>
          <% end %>
          <% if @group.user == current_user %>
            <small class="text-muted">Joined on : <%= @group.created_at.strftime('%b %Y') %></small>
          <% end %>
          <% if current_user.groups.include?(@group) %>
            <%= button_to "Unfollow Group", unfollow_group_path(@group), method: :delete, class: 'btn btn-danger btn-sm mt-2 mb-2' %>
          <% else %>
            <%= button_to "Follow Group", follow_group_path(@group), method: :post, class: 'btn btn-primary btn-sm mt-2 mb-2' %>
          <% end %>
          <% if @group.users.count > 0 %>
            <small class="text-primary mt-3">
              <%= link_to group_followers_group_path(@group), style: 'text-decoration:none;' do %>
                <%= pluralize(@group.users.count, 'Follower') %>
              <% end %>
              </small>
          <% end %>

        </div>
      </div>
      <div class="card mb-3 shadow">
        <div class="card-body">
          <%= link_to 'Groups', groups_path, style: 'text-decoration:none;' %>
          <% @groups.each do |group|%><br>
            <%= link_to group_path(group), style: 'text-decoration:none;' do %>
              <small class="text-dark"><%= group.name %></small>
            <% end %>
          <% end %>
          <hr>
          <div class="row">
            <div class="col-lg-10">
              <%= link_to "Events", user_my_events_path(current_user), style: 'text-decoration:none;'  %>
            </div>
            <div class="col-lg-2">
              <%= link_to new_event_path, data: { controller: 'bs-modal-form' } do %>
                <i class="fa-solid fa-plus"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-7 col-md-8 col-sm-12 mt-2">
      <div class="card shadow mt-2 mb-2">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-8"> 
              <h4><%= @group.name %></h4>
              <small class="text-muted"><%= @group.group_type %> Listed</small>
              <p><b>Industry : </b><%= @group.industry %></p>
              <p><b>Location : </b><%= @group.location %></p>
              <p><b>Created : </b><%= @group.created_at.strftime('%Y-%m-%d') %></p>
            </div>
            <% if @group.image.present? %>
              <div class="col-lg-4">
                <%= image_tag @group.image, class: 'w-100' %>
              </div>  
            <% end %>
            <div data-controller="show-more">
              <div data-show-more-target="description">
                <p><b>Description : </b><%= simple_format @group.description %></p>
              </div>
              <div class="d-flex justify-content-end" >
                <button 
                  data-action="click->show-more#toggleVisibility" 
                  data-show-more-target="toggleButton" 
                  class="btn btn-light text-primary btn-sm mt-2">
                  Show More
                </button>
              </div>
            </div>
          </div>
        </div>        
      </div>
      <div class="card mt-2 mb-2 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col-md-1 col-12 mb-2 d-grid">
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image, style: "width: 50px;", class: "mt-2 border border-1 rounded-circle" %>
              <% else %> 
                <%= image_tag 'human.avif', style: "width: 50px;", class: "mt-2 border border-1 rounded-circle" %>
              <% end %>
            </div>
            <div class="col-md-11 col-12 mt-1 mb-3 d-grid">
              <%= link_to new_post_path(group_id: @group.id), class: "d-flex btn btn-outline-light text-dark border py-2 rounded-pill mr-1 pr-5 mt-2", data: { controller: "bs-modal-form" } do %>
              Start a Post
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'home/post_sort' %>        
      <%= render 'groups/group_posts' %>
    </div>
    <div class="col-lg-2 mt-3">
      <div class="card shadow text-center admin-card">
        <div class="card-body">
          <h5 class="mb-3 admin-heading">Group Admin</h5>
          <% if @group.user.present? %>
            <%= link_to member_path(@group.user), style: "text-decoration:none;" do %>
              <% if @group.user.image.attached? %>
                <%= image_tag @group.user.image, class: "admin-image mb-2 border border-1 rounded-circle", style: 'width:50px;' %>
              <% else %> 
                <%= image_tag 'human.avif', class: "admin-image mb-2 border border-1 rounded-circle", style: 'width:50px;' %>
              <% end %>
              <h6 class="text-dark admin-name"><%= @group.user.name %></h6>
              <small class="text-muted admin-title"><%= @group.user.profile_title %></small>
            <% end %>
          <% else %>
            <p>No admin found for this group</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>