config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/generate_otp', to: 'users/sessions#generate_otp', as: :generate_otp
    get '/session_id/:id', to: 'users/sessions#session_id', as: :session_id
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  
  resources :pages, controller: 'pages' do
    member do
      post :follow
      delete :unfollow
    end
  end

  resources :groups do
    member do
      post 'follow'
      delete 'unfollow'
      get 'followers', to: 'groups#followers', as: 'group_followers'
    end
  end
  
  # for hide & unhide the posts
  resources :posts do
    member do
      post 'hide'
      post 'undo_hide'
      post 'toggle_hide'
      post 'repost_with_thought', to: 'reposts#repost_with_thought', as: 'repost_thought'
    end
    resources :reposts
    resources :comments
    resources :user_reactions, only: [:create, :destroy]
  end

  resources :events do
    collection do
      get 'calendar', to: 'events#calendar'
      post 'calendar_events', to: 'events#create_calendar_event'
    end
  end


  get 'hidden_posts', to: 'posts#hidden'

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get '/search_results', to: 'search#results', as: 'search_results'
  
  get '/home', to: 'home#index', as: :home
  get '/home/sort', to: 'home#sort', as: :home_sort
  
  get 'member/:id', to: 'members#show', as: :member  
  get 'member/:id/edit', to: 'members#edit', as: :edit_member
  patch 'member/:id', to: 'members#update', as: :update_member

  get 'members/fetch_country_states', to: 'members#fetch_country_states', as: :fetch_country_states

  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: 'update_member_personal_details'

  get 'member-connections/:id', to: 'members#connections', as: 'member_connections'

  resources :articles  
  resources :jobs
  resources :job_categories
  resources :work_experiences
  resources :connections
  resources :skills
  resources :shares, only: [:new, :create,:index]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]

  resources :users do
    resources :posts
    resources :jobs
    resources :my_jobs, only: [:index]
    resources :my_events, only: [:index]
    resources :my_articles, only: [:index]
  end

  resources :members, controllers: 'members' do
    member do
      post :follow
      delete :unfollow
      get :followers_and_following
    end
    collection do
      get :fetch_country_states
    end
  end

  resources :followers, only: [:show] do
    member do
      get :show_followers
    end
  end
end

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
  <div class="<%= flash_class(key.to_sym)%> alert-dismissible fade show" role="alert">
    <% unless value == true %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= value %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-lg-4 col-md">
      <small class="d-block mb-3 text-muted">Company @ 2022-2023</small>
    </div>
    <div class="col-lg-4">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">About Us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Contact Us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Our Mission</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-4">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Blogs</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Careers</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Profiles</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to "Dev Community", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li>
            <%#= link_to 'My Profile', member_path(current_user), class:'nav-link active'%>  
          </li>
          <li>
            <%= link_to 'My Network', connections_path, id: "add-my-network-link", class:'nav-link active'%>  
          </li>
          <li>
            <%= link_to 'Job', jobs_path, class:'nav-link active', id: 'users_job' %>  
          </li>
          <li>
            <%= link_to "Shared Posts", shares_path, class:'nav-link active' %>
          </li>
          <li>
            <%= link_to "Events", events_path, class: 'nav-link active' %>
          </li>
          <li>
            <%= link_to "Hidden Posts", hidden_posts_path, class: "nav-link active" %>
          </li>
          <li>
            <%= link_to "Pages", pages_path, id: "pages", class: 'nav-link active'  %>
          </li>
          <li>
            <%= link_to "Articles", articles_path, class: 'nav-link active'  %>
          </li>
          <li>
            <%= link_to notifications_path, class: "btn btn-primary position-relative" do %>
                <i class="fa-solid fa-bell fa-lg"></i>
                <% if current_user.unviewed_notifications_count > 0 %>
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    <%= current_user.unviewed_notifications_count > 0 ? current_user.unviewed_notifications_count : '0' %>
                    <span class="visually-hidden">unread messages</span>
                  </span>
               <% end %>   
            <% end %>
          </li>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, id: "add-signout-link", data: { turbo_method: :delete, turbo_confirm: 'Are You Sure to Sign Out ?' }, class: 'nav-link active' %>
          </li>
        <% end %>  
      </ul>
      <% if user_signed_in? %>
       <div class="d-flex justify-content-end col-lg-2" >
        <%= render partial: "search/form", locals: { results: [] } %>
      </div>
      <% end %>
    </div>    
  </div>
</nav>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
<div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="bsTurboModalLabel" aria-hidden="true" data-controller="bs-modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bsTurboModalLabel"><%= modal_title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= render form_partial %>
    </div>
  </div>
</div>
<% end %>