config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get '/generate_otp', to: 'users/sessions#generate_otp', as: :generate_otp
    get '/session_id/:id', to: 'users/sessions#session_id', as: :session_id
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  
  resources :pages, controller: 'pages' do
    member do
      post :follow
      delete :unfollow
    end
  end

  resources :groups do
    member do
      post 'follow'
      delete 'unfollow'
      get 'followers', to: 'groups#followers', as: 'group_followers'
    end
  end
  
  # for hide & unhide the posts
  resources :posts do
    member do
      post 'hide'
      post 'undo_hide'
      post 'toggle_hide'
      post 'repost_with_thought', to: 'reposts#repost_with_thought', as: 'repost_thought'
    end
    resources :reposts
    resources :comments
    resources :user_reactions, only: [:create, :destroy]
  end

  resources :events do
    collection do
      get 'calendar', to: 'events#calendar'
      post 'calendar_events', to: 'events#create_calendar_event'
    end
  end


  get 'hidden_posts', to: 'posts#hidden'

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get '/search_results', to: 'search#results', as: 'search_results'
  
  get '/home', to: 'home#index', as: :home
  get '/home/sort', to: 'home#sort', as: :home_sort
  
  get 'member/:id', to: 'members#show', as: :member  
  get 'member/:id/edit', to: 'members#edit', as: :edit_member
  patch 'member/:id', to: 'members#update', as: :update_member

  get 'members/fetch_country_states', to: 'members#fetch_country_states', as: :fetch_country_states

  get 'edit_description/:id', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: 'update_member_personal_details'

  get 'member-connections/:id', to: 'members#connections', as: 'member_connections'

  resources :articles  
  resources :jobs
  resources :job_categories
  resources :work_experiences
  resources :connections
  resources :skills
  resources :shares, only: [:new, :create,:index]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]

  resources :users do
    resources :posts
    resources :jobs
    resources :my_jobs, only: [:index]
    resources :my_events, only: [:index]
    resources :my_articles, only: [:index]
  end

  resources :members, controllers: 'members' do
    member do
      post :follow
      delete :unfollow
      get :followers_and_following
    end
    collection do
      get :fetch_country_states
    end
  end

  resources :followers, only: [:show] do
    member do
      get :show_followers
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:likes, :comments, :reposts, :user_reactions, user: [:reposts, :groups, :user_reactions, :follows, :notifications, :articles, image_attachment: :blob], images_attachments: :blob).order(created_at: :desc)
    @post_likes_count = Post.joins(:likes).group('posts.id').count
    comment_counts = Comment.where(commentable_id: @posts.map(&:id), 
                     commentable_type: 'Post')
                     .group(:commentable_id)
                     .count

    # Now, you can create a hash where keys are post IDs and values are comment counts
    @post_comment_counts = comment_counts.transform_keys(&:to_i)


    # user_reaction_counts = UserReaction.where(reactable_id: @posts.map(&:id), 
    #                  reactable_type: 'Post')
    #                  .group(:reactable_id)
    #                  .count

    # Now, you can create a hash where keys are post IDs and values are comment counts
    #@post_user_reaction_counts = user_reaction_counts.transform_keys(&:to_i)
    
    # for showing the total connected user ids count of current user
    @total_connections = Connection.where('user_id = ? OR connected_user_id = ?', current_user.id, current_user.id).where(status: 'accepted')
    @groups = Group.includes(:user)
    @reposts = Repost.where(post_id: @posts.map(&:id)).group_by(&:post_id)
  end

  def sort
    common_includes = [:likes, user: [image_attachment: :blob], images_attachments: :blob]

    sort_order = case params[:sort_by]
    when 'alphabetical'
      { order_column: :title, order_direction: :asc }
    when 'alphabetical_reverse'
      { order_column: :title, order_direction: :desc }
    when 'time_posted_reverse'
      { order_column: :created_at, order_direction: :asc }
    when 'time_posted'
      { order_column: :created_at, order_direction: :desc }
    else
      { order_column: :created_at, order_direction: :desc }
    end

    @groups = Group.includes(:user)

    @posts = Post.includes(common_includes).order(sort_order[:order_column] => sort_order[:order_direction])
    @post_likes_count = Post.joins(:likes).group('posts.id').count

    # Add the logic for calculating comment_counts here
    comment_counts = Comment.where(commentable_id: @posts.map(&:id), 
      commentable_type: 'Post')
      .group(:commentable_id)
      .count

    # Now, you can create a hash where keys are post IDs and values are comment counts
    @post_comment_counts = comment_counts.transform_keys(&:to_i)

    respond_to do |format|
      format.html { render 'index' } # Render the index view with sorted posts
      format.turbo_stream
    end
  end

  # def connections
  #   @user = User.find(params[:id])
  #   total_users = if params[:mutual_connections].present?
  #     User.where(id: current_user.mutually_connected_ids(@user))
  #   else
  #     User.where(id: @user.connected_user_ids)
  #   end
  # end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_like_and_reposts.html.erb
<!-- for display the names of users who liked & repost a post and show the count of remaining users into the modal popup -->
<% if post.likes.present? || post.reposts.present? %>
  <div class="row border border-1 mt-3 mb-3">
    <div class="col-lg-6 mt-2 mb-2">
      <% likes = post.likes.includes(:user) %>
      <% if likes.present? %>
        <% first_user = likes.first.user %>
        <% other_users = likes[1..] %>
        <div>
          <span>
            <% has_liked = current_user && likes.pluck(:user_id).include?(current_user.id) %>
            <% if has_liked %>
              Liked by You
            <% else %>
              Liked by
              <% if other_users.present? %>
                <%= link_to first_user.name, member_path(first_user), style: 'text-decoration:none;' %>
              <% else %>
                <%= link_to first_user.name, member_path(first_user), style: 'text-decoration:none;' %>
              <% end %>
            <% end %>
            <% if other_users.present? %>
              <% if has_liked %>
                and
              <% end %>
              <a href="#" data-bs-toggle="modal" data-bs-target="#likeModal-<%= post.id %>">
                <%= other_users.size > 1 ? "#{other_users.size} others" : "#{other_users.size} other" %>
              </a>
              liked
              <!-- Modal -->
              <div class="modal fade" id="likeModal-<%= post.id %>" tabindex="-1" aria-labelledby="likeModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="likeModalLabel-<%= post.id %>">Users Who liked This Post</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <% likes.each do |like| %>
                        <% user = like.user %>
                        <% like_time_ago = time_ago_in_words(like.created_at) %>
                        <div class="d-flex align-items-center mb-2">
                          <%= image_tag user.image, alt: "User Image", style: "width: 30px; height: 30px; border-radius: 50%; object-fit: cover;" if user.image.attached? %>
                          <p class="ms-2 mb-0">
                            <% if current_user && current_user == user %>
                              liked by You - <%= like_time_ago %> ago
                            <% else %>
                              <%= link_to user.name, member_path(user), style: 'text-decoration:none;' %> - <%= like_time_ago %> ago
                            <% end %>
                          </p>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
    <div class="col-lg-6 mt-2 mb-2 d-flex justify-content-end">
      <% reposts = post.reposts.includes(:user) %>
      <% if reposts.present? %>
        <% first_user = reposts.first.user %>
        <% other_users = reposts[1..] %>
        <div>
          <span>
            <% has_reposted = current_user && reposts.pluck(:user_id).include?(current_user.id) %>
            <% if has_reposted %>
              Reposted by You
            <% else %>
              Reposted by
              <% if other_users.present? %>
                <%= link_to first_user.name, member_path(first_user), style: 'text-decoration:none;' %>
              <% else %>
                <%= link_to first_user.name, member_path(first_user), style: 'text-decoration:none;' %>
              <% end %>
            <% end %>
            <% if other_users.present? %>
              <% if has_reposted %>
                and
              <% end %>
              <a href="#" data-bs-toggle="modal" data-bs-target="#repostModal-<%= post.id %>">
                <%= other_users.size > 1 ? "#{other_users.size} others" : "#{other_users.size} other" %>
              </a>
              reposted
              <!-- Modal -->
              <div class="modal fade" id="repostModal-<%= post.id %>" tabindex="-1" aria-labelledby="repostModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="repostModalLabel-<%= post.id %>">Users Who Reposted This Post</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <% reposts.each do |repost| %>
                        <% user = repost.user %>
                        <% repost_time_ago = time_ago_in_words(repost.created_at) %>
                        <div class="d-flex align-items-center mb-2">
                          <%= image_tag user.image, alt: "User Image", style: "width: 30px; height: 30px; border-radius: 50%; object-fit: cover;" if user.image.attached? %>
                          <p class="ms-2 mb-0">
                            <% if current_user && current_user == user %>
                              Reposted by You - <%= repost_time_ago %> ago
                            <% else %>
                              <%= link_to user.name, member_path(user), style: 'text-decoration:none;' %> - <%= repost_time_ago %> ago
                            <% end %>
                          </p>
                        </div>
                        <div class="container mb-4">
                          <%= link_to post_path(post), style: 'text-decoration:none; color:black;' do %>
                            <h5 class= "text-primary">Title : <%= post.title %></h5>
                              <p><%= truncate(post.description, length: 150) %></p>
                                <% first_image = post.images.first %>
                                <% if first_image.present? %>
                                  <% if first_image.content_type.include?("image") %>
                                    <a href="<%= rails_blob_path(first_image) %>" class="post_images me-2 mb-3 mt-3" data-turbolinks="false" data-mfp-title="<%= post.title %>">
                                      <%= image_tag first_image, style: 'width: 370px; height: 280px; max-width: 100%;', class: 'mt-2 mb-2 border border-1' %>
                                    </a>
                                  <% else %>
                                    <div class="bg-dark text-center">
                                      <%= video_tag rails_blob_path(first_image), autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video", controls: true, type: 'video/mp4', style: "max-width: 100%; height: 320px;" do %>
                                        Your browser does not support the video tag.
                                      <% end %>
                                    </div>
                                  <% end %>
                                <% end %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/_post_sort.html.erb
<div class="col-lg-12 mx-auto mb-2 d-flex justify-content-end">
  <%= form_tag(home_sort_path, method: :get, class: "row g-2", data: { controller: 'post-sort' }) do |form| %>
    <div class="col-auto">
      <%= label_tag 'sort_by', 'Sort By : ', class: 'fw-bold mt-2' %>
    </div>
    <div class="col-auto">
      <%= select_tag 'sort_by', options_for_select([
        ['Newest', 'time_posted'],
        ['Oldest', 'time_posted_reverse'],
        ['A-Z', 'alphabetical'],
        ['Z-A', 'alphabetical_reverse']
      ], params[:sort_by]), class: "form-select", id: "sort_by", data: { action: 'post-sort#update', post_sort_target: 'select' } %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container col-lg-10 mx-auto mt-3 my-container">
  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-12 mt-3">
      <div class="card text-center mb-2 shadow current_user_profile">
        <div class="card-body">
          <% if current_user.image.attached? %>
            <%= image_tag current_user.image, style: "width: 130px; max-width:100%;", class: 'border border-1 rounded-circle mb-3 mt-3' %>
          <% else %> 
            <%= image_tag 'human.avif', class: "border border-1 rounded-circle mb-3 mt-3", style: "width: 130px; max-width:100%;" %>
          <% end %>
          <%= link_to member_path(current_user), id: "add-user-profile-link", style: "text-decoration:none;" do %>
            <h5 class="text-dark"><%= current_user.name %></h5>
          <% end %>
          <small class=" text-muted"><%= current_user.profile_title %></small>
          <hr>
          <p>
            <div id="connection-count">
              <%= link_to pluralize((@total_connections ? @total_connections.count : 0), 'connection'), member_connections_path(current_user), id: "add-connection-link", style: "text-decoration:none;" %>
            </div>
          </p>
          <hr>
          <%= link_to 'My Job', user_my_jobs_path(current_user), id: 'my-job', style: 'text-decoration:none;'%> 
          <hr>
          <%= link_to 'My Post', user_posts_path(current_user), id: "add-user-post-link", style: 'text-decoration:none;'%> 
          <hr>
          <%= link_to "My Followers", followers_and_following_member_path(current_user), id: "add-my-followers-link", style: 'text-decoration:none;' %> 
          <hr>
          <%= link_to "My Article", user_my_articles_path(current_user), id: "my-article", style: 'text-decoration:none;' %> 
          <hr>
          <%= link_to "My Events", user_my_events_path(current_user), id: "my_event", style: 'text-decoration:none;'  %>
          <hr>
          <%= link_to 'View Calendar', calendar_events_path, id:"viewCalendarButton", style: 'text-decoration:none;' %>
        </div>
      </div>
      <div class="card mb-2 shadow">
        <div class="card-body">
          <%= link_to 'Groups', groups_path, style: 'text-decoration:none;' %>
            <% @groups.each do |group|%><br>
              <%= link_to group_path(group), style: 'text-decoration:none;' do %>
               <small class="text-dark"><%= group.name %></small>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-9 col-md-8 col-sm-12 mt-2">
      <div class="card mt-2 mb-2 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col-md-1 col-12 mb-2 d-grid">
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image, style: "width: 50px;", class: "mt-2 border border-1 rounded-circle" %>
              <% else %> 
                <%= image_tag 'human.avif', style: "width: 50px;", class: "mt-2 border border-1 rounded-circle" %>
              <% end %>
            </div>
            <div class="col-md-11 col-12 mt-1 mb-3 d-grid">
              <%= link_to new_post_path, class: "d-flex btn btn-outline-light text-dark border py-2 rounded-pill mr-1 pr-5 mt-2", id: 'add-post-link', data: { controller: "bs-modal-form" } do %>
              Start a Post
              <% end %>
              <div class="row mt-3">
                <div class="col-lg-2">
                  <%= link_to new_event_path, id: 'add-event-link', data: { controller: 'bs-modal-form' }, style: "text-decoration:none;" do %>
                    <i class="fa-regular fa-calendar-days me-1 text-dark"></i>
                    Add Event
                  <% end %>
                </div>
                <div class="col-lg-3">
                  <%= link_to new_article_path, id: "add-article-link", data: { controller: 'bs-modal-form' }, style: "text-decoration:none;" do %>
                    <i class="fa-solid fa-newspaper me-1 text-dark"></i>
                    Write Article
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= render 'home/post_sort' %>        
      <%= render 'home/posts' %>
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
</div>